[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/medicineSearch"
  to = "/.netlify/functions/medicineSearch"
  status = 200
